### ISSUE TITLE
Admin inlines. Adding inline appends froala to all text fields

### ISSUE THREAD

**Issue by Mykyta-Chernenko** [froala/django-froala-editor#63] opened 2019-01-18 14:27 UTC
https://github.com/froala/django-froala-editor/issues/40

Solution of this issue is wrong. 
It both appends froala to all text fields and not only to froala fields
and doesn't add any options

**Comment by xtranophilist** [comment] 2019-01-20 12:35
Hi @marakaci, thanks. Yes, this is an open issue and duplicate of #53.
We will work on it. If you already have a solution, please send us a PR.

**Closed as completed by xtranophilist** 2019-01-20 12:35 UTC
Labels: duplicate
